### ISSUE TITLE
About the Design of Adding Scripts

### ISSUE THREAD

**Issue by duanhongyi** [drycc-addons/helmbroker#10]
1、 在每个addon中添加scripts 目录，比如说addons/seaweedfs/3/256中增加个 scripts 目录。
2、目录内部有如下几个文件：
       pre_create.sh
       post_create.sh
       pre_update.sh
       post_update.sh
       pre_destroy.sh
       post_destroy.sh
3 、其中 pre开头的是在执行helm命令之前执行， 主要作用是执行安装前的例行检查等工作，如果返回正确值之后才能运行 helm 命令。
4 、post 开头的是在执行helm命令之后执行，比如说是清理等工作，运行结果不影响已经执行过的 helm 命令。

这个脚本设计之初是为了解决通过 helm 无法升级statefulset pvc 的问题。

**Comment by EamonZhang** [comment]
post_destroy.sh 释放postgresql-cluster 后清除名称为 postgresql-config 的 service 。

原因： 该service 为patroni 创建， 当所有的pod被清理后才能删除。 尝试过在addons 中删除，不能保证删除service 和 pod 的顺序。只要还有一个pod 存在，postgresql-config 就会被重新创建。导致无法清理干净。

**Comment by duanhongyi** [comment]
check prometheus alertmanager rules
https://github.com/cloudflare/pint

**Comment by duanhongyi** [comment]
complete
